type User {
	name: String
	email: Email
	age: Int
	gender: Gender
	lastLogin: DateTimeISO
}

enum Gender {
	Male
	Female
	Others
}

type createUserRes {
	code: Int
	success: Boolean
	message: String
	payload: User
}

input UserInput {
	name: String!
	email: Email!
	age: Int
	gender: Gender
	password: String!
}

type loginUserRes {
	code: Int
	success: Boolean
	message: String
	payload: User
	accessToken: String
}

type LoginUserData {
	user: User!
	accessToken: String!
	refreshToken: String!
}

union LoginUserResult =
	  LoginUserData
	| BadUserInput
	| NotFound
	| InternalServerError

type UserExists {
	message: String!
	email: Email
}

union CreateUserResult = User | BadUserInput | UserExists | InternalServerError

type Mutation {
	createUser(form: UserInput!): CreateUserResult
	loginUser(email: Email!, password: String!): LoginUserResult
}

union UserResult =
	  User
	| NotFound
	| InternalServerError
	| Unauthorized
	| Forbidden

type Query {
	getUser: UserResult! @auth
}
